experiment: 
  debuging : False

num_epochs : 20
num_workers : 8
batch_size : 32
valid_size : 0.2

dir:
  input_dir : ./input/data
  image_dir : ./input/data/{}/images
  checkpoint_dir : ./checkpoint
  #load_dir : ./checkpoint/resnet-18.pth

model_name : resnet-18


